# Generated by Django 3.1.2 on 2020-12-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Amende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_amende', models.CharField(max_length=50)),
                ('desciption', models.TextField(null=True)),
                ('nombre_victimes', models.IntegerField(default=0)),
                ('prix_penalite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BD_Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNI', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('contact', models.IntegerField(unique=True)),
                ('date_naissance', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('statut_matrimoniale', models.IntegerField(choices=[(1, 'Célibataire'), (2, 'Marié'), (3, 'Compliqué')])),
            ],
        ),
        migrations.CreateModel(
            name='Fuyard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_infraction', models.IntegerField(default=0)),
                ('fuyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amande_routier.bd_police')),
            ],
        ),
        migrations.CreateModel(
            name='Controlleur_Routier',
            fields=[
                ('bd_police_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='amande_routier.bd_police')),
                ('num_identification', models.IntegerField(unique=True)),
                ('nombre_amende', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            bases=('amande_routier.bd_police',),
        ),
        migrations.CreateModel(
            name='Matricule_Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=15, unique=True)),
                ('carte_grise', models.CharField(max_length=20, unique=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amande_routier.bd_police')),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amande_routier.amende')),
                ('fuyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amande_routier.fuyard')),
                ('policier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amande_routier.controlleur_routier')),
            ],
        ),
    ]
