# Generated by Django 3.1.2 on 2020-12-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amande_routier', '0002_auto_20201225_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricule_vehicule',
            name='carte_grise',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
