# Generated by Django 3.1.2 on 2020-12-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amande_routier', '0003_auto_20201225_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuyard',
            name='matricule_vehicule',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fuyard',
            name='fuyeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amande_routier.bd_police'),
        ),
        migrations.AlterField(
            model_name='fuyard',
            name='nombre_infraction',
            field=models.IntegerField(default=1),
        ),
    ]
