# Generated by Django 3.1.2 on 2021-01-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amande_routier', '0004_auto_20201225_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuyard',
            name='nombre_infraction',
            field=models.IntegerField(default=0),
        ),
    ]
